# Generated by Django 4.2.5 on 2024-03-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('disease', models.CharField(default='', max_length=100)),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile_pictures/')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
