# Generated by Django 4.2.5 on 2024-03-11 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_remove_usermodel_email_remove_usermodel_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='pid',
            new_name='patient_id',
        ),
    ]
